name: easynote
services:
  - name: backend
    internal_ports: 
      - 5000
    image:
      registry_type: DOCR
      repository: agile/backend
      digest: ${BACKEND_DIGEST}
    envs:
      - key: MONGODB_URI
        value: ${MONGO_URI}
  - name: frontend
    http_port: 8080
    image:
      registry_type: DOCR
      repository: agile/frontend
      digest: ${FRONTEND_DIGEST}
